### ISSUE TITLE
Tab display name changed "+" to blank space(code is 32)

### ISSUE THREAD

**Issue by TonyLi2013** [microsoftgraph/microsoft-graph-docs#11027]
When use Graph API to add Tab to a channel, then use Graph API to list channels, we found the display name change "+" to blank space which ASCII code is 32, the post body we use is:

POST https://graph.microsoft.com/v1.0/teams/{id}/channels/{id}/tabs
{
  "displayName": "My+Con to so+Tab",
  "teamsApp@odata.bind" : "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/0ae35b36-0fd7-422e-805b-d53af1579093",
  "webUrl": "xxx",
            "configuration": {
                "entityId": "sharepointtab_0.5155599342889783",
                "contentUrl": "xxx",
                "removeUrl": null,
                "websiteUrl": "xxx"
            }
}

The response is:
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#teams('c3c6e6f1-30bf-448a-a692-8c6b7223eeaa')/channels('19%3A0e9068a6eec24b7387836fad7b426284%40thread.tacv2')/tabs/$entity",
    "id": "2bb489f1-a145-4c72-b50d-c5cb7cf50af1",
    "displayName": "My Con to so Tab",
    "webUrl": "xxx",
    "configuration": {
        "entityId": "sharepointtab_0.5155599342889783",
        "contentUrl": "xxx",
        "removeUrl": null,
        "websiteUrl": "xxx"
    }
}

You can see the "+" in display name changed to blank space, but blank space is still blank space, which we can not identify the real name of the tab, is "+" a not allowed char in Tab name?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: feddb622-23f9-430a-1235-c72e614f455b
* Version Independent ID: 349d6f59-c24d-94e7-ca5e-7b660d8a5345
* Content: [Add tab to channel - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/channel-post-tabs?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/channel-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/channel-post-tabs.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by TonyLi2013** [comment]
any update on this issue?

**Comment by Abhijit-MSFT** [comment]
@TonyLi2013, Yes, I see that when "+" is added in Display Name, it is getting replaced with blank space (in list tabs api) but the Tab name in the Teams is displayed properly. Where in this works fine with "-" and "*".
I am checking it with concerned team - I will let you know as soon as i hear back from them. Thanks for reaching out.

**Comment by TonyLi2013** [comment]
@Abhijit-MSFT thanks for your reply, waiting for your update.

**Comment by Manish-MSFT** [comment]
@TonyLi2013 : We have raised a bug, will update here once the issue is resolved.

**Comment by Manish-MSFT** [comment]
@TonyLi2013  : This issue has been resolved. Please check at your end.

**Comment by TonyLi2013** [comment]
Hi @Manish-MSFT The issue still exist after checking from on my end, the results from list tab api still replaced + to blank space.

**Comment by Mallipriya-MSFT** [comment]
@TonyLi2013, Could you please try it with latest Teams version?

**Comment by Mallipriya-MSFT** [comment]
Hi @TonyLi2013, The issue is resolved. We tested it from our end and got it working.  Could you please check again at your end.

**Comment by TonyLi2013** [comment]
Hi @Manish-MSFT Sorry for the delay reply, I tested this again and the issue has been resolved indeed, thanks for your help, much appreciated! you can close this case now.

**Comment by Trinetra-MSFT** [comment]
Closing this issue
