### ISSUE TITLE
Table of content disappears when scroll down

### ISSUE THREAD

**Issue by Hongbo-Miao** [microsoftgraph/microsoft-graph-docs#1680]
https://developer.microsoft.com/en-us/graph/docs/concepts/overview

When you scroll down, the table of content disappears.

Tried Chrome, Firefox, Safari.

**Comment by Lauragra** [comment]
Thanks, Hongbo! This is a known issue; we're working with engineering on it.

**Comment by Lauragra** [comment]
This issue has been resolved. Thanks.

**Comment by Hongbo-Miao** [comment]
@Lauragra that page solves.
I am not sure other pages, but this page still have the issue https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/message_get

**Comment by Hongbo-Miao** [comment]
@Lauragra that page solves.
However, some pages still have the issue, such as
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/message_get
https://developer.microsoft.com/en-us/graph/docs/concepts/query_parameters

**Comment by Lauragra** [comment]
Try refreshing your cache or in-private browser?

**Comment by Hongbo-Miao** [comment]
Oh, you are right. Thanks
