### ISSUE TITLE
Download content - CORS support?

### ISSUE THREAD

**Issue by Mike-Bell** [microsoftgraph/microsoft-graph-docs#43]
It seems that the call to download a file's content does not support cross-origin requests. The /content request results in a 302 (which the browser rejects in accordance with the CORS spec). It seems that the url that you are being redirected to doesn't support CORS anyway - so there's multiple layers of failure.

This seems like the same underlying issue as http://stackoverflow.com/questions/27068647/onedrive-cors-download-in-javascript
If this is truly a limitation of the API, this should be made widely known and very clear in the docs.

**Comment by martellaj** [comment]
This is an issue that the OneDrive API team is already aware of. Thanks for the details!

**Comment by Mike-Bell** [comment]
@martellaj Thanks for the response! Is this to imply that there is no known workaround for fetching a file's contents directly from browser-side JavaScript without resorting to proxying through a server?

**Comment by martellaj** [comment]
Not that I know of right now. I've raised this issue before and know that most of the calls do work with CORS, but seems like there's a couple that slipped through the cracks. I'll report back when I hear more from the right people. 👍

**Comment by Mike-Bell** [comment]
Thanks @martellaj. If you happen to hear anything about whether or not this will be addressed at some point, I'd love to hear it. If there's some internal repository for third-party developer feedback, give this issue a big fat +1 from me :sweat_smile: 

As you seem to appreciate, this is a pretty annoying limitation for people wanting to do modern web development against onedrive.

**Comment by rgregg** [comment]
Hi Mike,

The URL that we redirect too is accessible via a browser because it doesn't require any custom headers (you don't need pass the authorization header to the final download URL). So once you can obtain the download URL directly (the URL that /content 302 redirects you to) then you're good to go.

When using the OneDrive API directly (instead of through Graph API) you can access this URL by requesting the @content.downloadUrl property using ?$select=id,@content.downloadUrl. However, this select statement is generating an error in the Graph API and so this method isn't available.

We're looking into how we can best resolve this and will post an update when we have a solution.

**Comment by Mike-Bell** [comment]
@rgregg Any update by chance on pure-javascript content downloading?

**Comment by rgregg** [comment]
Hi Mike. We've got a bug tracking this issue and I'm working to get an ETA for it being resolved. December tends to be a pretty slow month for bug fixes and deployments, so I'm expecting to see this get resolved quickly now that it's Jan. I'll ping back here with more information when I have it.

**Comment by Mike-Bell** [comment]
> The URL that we redirect too is accessible via a browser because it doesn't require any custom headers (you don't need pass the authorization header to the final download URL). So once you can obtain the download URL directly (the URL that /content 302 redirects you to) then you're good to go.

I'm pretty sure that doesn't make it accessible via browser. Not having custom headers means you don't need a preflight. You still need to follow the rest of the spec though (i.e. access-control headers on the response). I bring this up because I changed my implementation such that my JS goes to my server for the downloadUrl, then follows the return pre-authenticated download url client side. I'm getting CORS issues (and no, I'm not passing up my Authorization header).

**Comment by marych** [comment]
@Mike-Bell This has been fixed and we're now returning the downloadUrl instance annotation for driveItem entities.

**Comment by Mike-Bell** [comment]
@marych you are indeed now returning the downloadUrl. But as I explained above, this does not actually fix the issue. The preauthenticated downloadUrl. Is *not* CORS compliant. You have to return CORS headers, even on simple GET requests with no custom headers, as the CORS spec indicates. I.e. I can request the resource and Fiddler shows a 200 response, but my browser (chrome) throws an error:

`XMLHttpRequest cannot load https://tscdev-my.sharepoint.com/personal/m_bell_o365_tsc-dev_co/_layouts/15/download.aspx?guestaccesstoken=<redacted>&docid=<redacted>&expiration=2016%2f02%2f23+15%3a37%3a56&userid=3&authurl=True&NeverAuth=True. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin '<my origin>' is therefore not allowed access.`

For the record my headers are:

Host: <my site>
Connection: keep-alive
Accept: application/json, text/plain, */*
Origin: <my site>
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36
Referer: <my site>
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8

**Comment by rgregg** [comment]
Hi @Mike-Bell: I'm aware of the issue with CORS and download.aspx and we're working on a fix.

**Comment by Mike-Bell** [comment]
Thanks for the update!

**Comment by jpatomic96** [comment]
Any update on this issue?

**Comment by rgregg** [comment]
@Mike-Bell @boulajp The download URL should be valid for GET requests now. We properly deal with the Origin header and return the CORS compatible response headers. However, any request that would require a preflight OPTIONS request will still fail.

**Comment by Superpluisje** [comment]
@rgregg I would like to inform you that there is still no 'Access-Control-Allow-Origin' header to be found on @content.downloadUrl URLs. Javascript is not able to download any content from OneDrive via XMLHttpRequests, which the documentation page @Mike-Bell mentioned before is still suggesting as working.

**Comment by oasmat83** [comment]
@rgregg any updates on the issue?

**Comment by rgregg** [comment]
It appears that the fix regressed (months ago). I'm investigating what's going on here.

**Comment by rgregg** [comment]
It does appear to be working per my guidance from Jun 2. You need to send a pure GET request, without headers, to the @downloadUrl value. Download URLs do not (and should not) have an Authorization header appended to the download, and without it the CORS request will succeed. The `Access-Control-Allow-Origin` header is returned.

If you add custom headers to the request, the request will fail, because the download URLs from SharePoint do not support the OPTIONS request necessary to enable an advanced CORS request.

**Comment by iamacarpet** [comment]
Trying to implement a OneDrive client for Chrome OS and this is still a major issue.

> However, any request that would require a preflight OPTIONS request will still fail.

That sucks as it means we can't specify a "Range" header when pulling content.
