### ISSUE TITLE
Listing subscriptions stopped working

### ISSUE THREAD

**Issue by billybraga** [microsoftgraph/microsoft-graph-docs#4644]
I recently started having problems with this endpoint; the subscriptions I created aren't listed in the GET subscriptions call, event if I can get the info of the created subscription with GET /subscription/{id}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c121424-d0a2-017c-e40d-3552ea66915c
* Version Independent ID: 999939fe-62c4-e17c-e0b6-d46ef100ecb5
* Content: [List subscriptions - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&tabs=cs#feedback)
* Content Source: [api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/subscription-list.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by notAmine** [comment]
I can confirm I'm also affected by this bug. This started happening in the last 24h

**Comment by apadev** [comment]
I have the same problem too even though the subscription is created successfully. The issue on the get prevents from checking/renewing the subscriptions.

**Comment by mjmamaril** [comment]
Same here suddenly graph subscription is not working as expected last 5 hrs ago. Creation of Subscription is successful but listening and renewing doesn't work well. May we have an update if this issue is valid.

**Comment by christianteh** [comment]
This has also affected us. We need to check list of subscription to decide whether we need to renew it every 24 hours

**Comment by jasonjoh** [comment]
I reproduce this as well. Checking with the team.

**Comment by imihalcea** [comment]
We are affected too, is there any workaround or fix announced?

**Comment by xkobal** [comment]
Same for me since 2 days. Do you have any updates ? All my users subscriptions are expiring...

**Comment by paul2newman** [comment]
https://graph.microsoft.com/v1.0/subscriptions

This was working last week. Yesterday it wasn't returning any subscriptions from the query. Today I'm getting the following error:

{
    "error": {
        "code": "ExtensionError",
        "message": "expirationDateTime cannot come before the current time.",
        "innerError": {
            "request-id": "6c7d08cb-xxxx-41ff-bfd4-ad52f8f6ca60",
            "date": "2019-05-23T08:35:11"
        }
    }
}

**Comment by mjmamaril** [comment]
Any updates on this so far guys.
hope we can fix this the soonest

**Comment by jbraband** [comment]
another confirmation of this issues with our app.

**Comment by christianteh** [comment]
it's working now guys

**Comment by xkobal** [comment]
I confirm, thank you.

**Comment by apadev** [comment]
It's working for me too. Can we have some sort of explanation ? My app recreated the subscriptions automatically and today they were all there, so I had to clean the mess and remove almost 250 subscriptions on the same resources.

Thanks

**Comment by jasonjoh** [comment]
Thanks for confirming that it's working again. Basically the problem was caused by a temporary service degradation due to a bug. The bug has been squashed so this should be working as expected now. Sorry for the inconvenience!

**Comment by erickbp** [comment]
Hi, @jasonjoh I think this is not resolved. I have been seeing this for a week now and it's happening right now.

Summary:

1. I can call https://graph.microsoft.com/v1.0/subscriptions and get my list of subscriptions correctly

2. but if I call GET https://graph.microsoft.com/v1.0/subscriptions/{Subscription ID HERE} to retrieve a specific subscription (from the list returned in step 1) I get the following:
{
    "error": {
        "code": "ExtensionError",
        "message": "There was an error processing a storage extension.",
        "innerError": {
            "request-id": "XXXXXXX",
            "date": "2019-06-06T14:30:01"
        }
    }
}

3. On the same token if I call PATCH https://graph.microsoft.com/v1.0/subscriptions/{Subscription ID HERE} to update a subscription I get the following:
{
    "error": {
        "code": "ExtensionError",
        "message": "Operation: Update; Exception: [Status Code: NotFound; Reason: The subscription with Id 'YYYYYYYY' is not found.]",
        "innerError": {
            "request-id": "XXXXXXX",
            "date": "2019-06-06T14:30:09"
        }
    }
}

BTW, in the update call, the error refers to a subscription ID that is not the one I passed as parameter and it is not a GUID either.

Please advise.

Thanks

**Comment by jasonjoh** [comment]
@piotrci any insights here? It sounds like a slightly different problem since listing subscriptions works. Should @erickbp open a support ticket via Azure Portal?

**Comment by mmamaril** [comment]
Hi All, 
I can confirm that we have the same issue encountered.

Create Subscription - OK
Get Specific Subscription - OK
Get List Subscription - Not working
Get Notification - Not working
Please update us on the progress of fixing this

**Comment by raimundasm** [comment]
Hello, 
it's happening again
I created subscribtion successfully  and received Id in response
I can view it via
https://graph.microsoft.com/v1.0/subscriptions/8a060360-24b8-4b5d-810e-5df2f02ef61a

{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#subscriptions/$entity",
    "id": "8a060360-24b8-4b5d-810e-5df2f02ef61a",
    ...
}
but calling
https://graph.microsoft.com/v1.0/subscriptions/
returns 
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#subscriptions",
    "@odata.nextLink": "https://graph.microsoft.com/v1.0/subscriptions/?$skiptoken=4ivzOLuAgPfoZRL9VlHjkC3vNI4MkMngxK62wIVhw16GMzP%252Bl%252FNAUj4PC80Lbb4qu%252F7dJGiEA%252BYF91yOc5n7npJQzM75UCN1SJYFJFfSE0E%253D",
    "value": []
}

**Comment by TylerJoaquinCrawford** [comment]
@mjmamaril, @raimundasm: I was experiencing the same issue over the last two days (created a workaround in the meantime), but this morning, `https://graph.microsoft.com/v1.0/subscriptions/` seems to be working again.

**Comment by hi1uo** [comment]
Getting same problem here. 

Sometimes works, sometimes keeps getting Error - `"message": "Get Subscriptions list is not supported for the API version 1.0."`

**Comment by GitHubPyhon** [comment]
Hello all.
Looks like it doesn't work again :(
List subscriptions - https://graph.microsoft.com/v1.0/subscriptions/
Can someone confirm it?
