### ISSUE TITLE
OneDrive personal createUploadSession - PUT returns 401 Unauthorized 

### ISSUE THREAD

**Issue by coreyrowell** [microsoftgraph/microsoft-graph-docs#495]
Using my business account the flow works fine. Only when using a personal account am I encountering the issue.
1. Successfully generate tokens using oauth2 flow
2. issue a POST to `https://graph.microsoft.com/beta/me/drive/root:/{path_to_item}:/createUploadSession` which gives the upload session url
3. Chunk the file into manageable chunks
4. Issue a PUT for each chunk to the returned upload session url

When using my personal account, the PUT request always returns a 401 Unauthorized. The folder structure is created in my OneDrive, but no file is uploaded.

I also hit the same 401 Unauthorized on PUT hitting the `https://api.onedrive.com/v1.0/drive/root:/{path_to_item}:/upload.createSession` url.

`Content-Length`, `Content-Range`, and `Authorization` headers are all correctly set.

**Comment by johnanburg** [comment]
I seem to be hitting the same issue on `api.onedrive.com`. Personal accounts receive a 401, the directory structure is created but the file isn't.

**Comment by daryltt** [comment]
I get a 401 error when uploading to a user's OneDrive for Business folder with an upload session.  It works fine when I upload a small file the normal way.

HTTP/1.1 401 Unauthorized
x-ms-diagnostics: 3000006;reason="Token contains invalid signature.";category="invalid_client"

{"error_description":"Invalid issuer or signature."}

Are these error messages the same for you?

I put the full details on [stackoverflow](http://stackoverflow.com/questions/39873718/getting-401-error-with-uploadsession-with-microsoft-graph)

**Comment by ificator** [comment]
FYI: I've reproed the issue on OneDrive Consumer.

I'll take a look at the OneDrive for Business issue soon.

**Comment by sameernyaupane** [comment]
Same issue here with using a personal account. Has this been solved yet? Thanks

**Comment by jensdotbruggeman** [comment]
Same issue here with OneDrive for Business.  It would be great if this could be solved.

**Comment by ificator** [comment]
We've tracked down the issue with consumer and are pushing a fix - should expect it to go live next week.

Taking a look at the business repro now.

**Comment by ificator** [comment]
You can read the StackOverflow link above for details, but I believe the issue @daryltt is encountering is related to the use of app-only tokens - OneDrive for Business via Graph does not, unfortunately, support their use at this time. @jensdotbruggeman, can you confirm that the same is true for your case? If not, I'll need some details of your failure to debug further.

**Comment by jensdotbruggeman** [comment]
The application is a daemon process, so indeed it is an app-only token.  This is a bit disappointing that I need another authentication/implementation for the use case when the file is >= than 4 MB.
In the case the file is larger than 4MB, I should access the OneDrive API for Business? Does this work correctly for daemon processes?

**Comment by ificator** [comment]
@jensdotbruggeman You'll get further with app-only tokens by calling the OneDrive API directly, however there are still some issues. Specifically, you cannot actually download the content of any file :(. There's a work around to that using CSOM that I can track down if you want to go down that path.

**Comment by jensdotbruggeman** [comment]
@ificator  I had some issues while using app-only tokens with OneDrive API since it assumes Certificated-based Manifest application registration.  (graph.microsoft.com did not require this.)
When I create a new certificate and adjust the AAD Application Manifest,  keyCredentials - Value on the new Azure portal it gives me an error "Can not update the application ... Details :  KeyValueMustBeNull"

So I'm blocked at that stage now :(

**Comment by daryltt** [comment]
Yea, I've thrown the towel in too.  It seems that there aren't enough complete examples for app-only scenarios.

**Comment by jensdotbruggeman** [comment]
I really want to achieve this, so with some help no problem to create an example for app-only scenario. :)

**Comment by ificator** [comment]
To those who were having issues with OneDrive for Consumers, the issue should now be resolved.

**Comment by jensdotbruggeman** [comment]
@daryltt  I created a blog post on how to perform this against the OneDrive API. 
https://dev0p.wordpress.com/2016/10/28/modern-interaction-with-office365-using-api-and-faas-architecture-part-2/

**Comment by sameernyaupane** [comment]
@ificator , I still have the problem with personal account. 

I am getting the following response:

```< HTTP/1.1 100 Continue
< HTTP/1.1 401 Unauthorized
< Content-Length: 70
< Server: Microsoft-IIS/8.5
< P3P: CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
< WWW-Authenticate: Bearer realm="OneDriveAPI", error="invalid_token", error_description="Auth error"
< X-MSNSERVER: BN1303____PAP176
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< X-QosStats: {"ApiId":0,"ResultType":2,"SourcePropertyId":0,"TargetPropertyId":42}
< X-ThrowSite: 4f37.717b
< X-AsmVersion: UNKNOWN; 0.1.0.0
< X-MSEdge-Ref: Ref A: 8EA2D7C9C544497FA280BB3B21D91579 Ref B: DC45F08F259994BAD8253F376C2B152B Ref C: Tue Nov  1 05:06:28 2016 PST
< Date: Tue, 01 Nov 2016 12:06:27 GMT
* HTTP error before end of send, stop sending
< 
* Closing connection 0````

My request seems to be all right, since other previous requests were all good.

Let me know if I am missing something.

**Comment by ificator** [comment]
@sameernyaupane are you providing an access token as part of the `PUT` request when uploading a fragment?

**Comment by sameernyaupane** [comment]
@ificator ,
I do have the Authorization header set.

This is my request 
```
*   Trying 204.79.197.213...
* Connected to api.onedrive.com (204.79.197.213) port 443 (#0)
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
* Server certificate:
* 	 subject: C=US; ST=WA; L=Redmond; O=Microsoft Corporation; OU=Microsoft Corporation; CN=storage.live.com
* 	 start date: 2016-02-11 00:34:50 GMT
* 	 expire date: 2018-02-10 00:34:50 GMT
* 	 subjectAltName: api.onedrive.com matched
* 	 issuer: C=US; ST=Washington; L=Redmond; O=Microsoft Corporation; OU=Microsoft IT; CN=Microsoft IT SSL SHA2
* 	 SSL certificate verify ok.
> PUT /up/eyJSZXNvdXJjZUlEIjoiQzY0MDUwNTQwQ0I5MDY2NiE2ODMiLCJSZWxhdGlvbnNoaXBOYW1lIjoid29yZHByZXNzLmxvYy0yMDE2MTEwMS0xMjA1NDQtNjA0LndwcmVzcyJ9/3m43Q-1IEKlkSnSh22hVREue_tRQCx6Xyp8AQBHzWPTnzoqCpvO6UoupiDcjKM_6yl/eyJOYW1lIjoid29yZHByZXNzLmxvYy0yMDE2MTEwMS0xMjA1NDQtNjA0LndwcmVzcyJ9/3wXmT58z4no_u5dHNRNvo9SQTx3FOKSMFPF02qGB-zDOVBkXpmmjkk59fYYh5DNq4og3OARUhnV4UwGaF8Q7vwN6Jq9U4KQUefOI6hvL7VZPcVN9eDfJyRExLuPH7paYBgEyKOCNhhOp4NyHc62nHAzD2-BNftej-Qp4k8Mszy6V6ati6UyVZxm1z5UCTTjzmf2Dcdws/8XLzaVWzjcCDcZ2_TrSTvOsKg8A6kJff5jC_L8pZFIUBl6NXE8s0J1n3CenSbvQCmxIuQ33vpfJ-eSYjQAK86USZSCTrI4Q6syKhOS_DrWI3Z4pbtVxJ8GZEJ7ow75-2Xstoaxfq3J2lDRgPlgsCv4-o7Gj6k147h6JO70KaduwtA06NB8j72umVkgRpVFJWDhDmVZh3/pFIBS-tSonXjShTXMEszDjZ3cjKTLxshDyHuC9eBUxddJMhhGy HTTP/1.1
Host: api.onedrive.com
Accept: */*
User-Agent: Test Agent
Authorization: Bearer EwA4A8l6BAAU1sPaz/0rP7ovs9bCsPzXhoCjrNEAAfT40aJUPmkBPdWoJQ0tXuMuhA9pibFnnfV//ewcIYseNs0L5jqQkOyo3bECrvJfRAPOYy3W/Ra0P02DAR4hD+tPFpMGBURbqYC9NU4xDyOiQZRfMZGhWRXhvus6trY5lhOwMA5e4wF+mjRVSPv+ZMVAFXvPot3wY8GELuiKMGde0hYVX2AvDMpQhQ8Kb5Nsgo1RJSkwt/liXyMeN6C5K5RjkqLQXrzNxPqRL8leRqwUe1Hw0h4z9rkBm/lRX5G8WB03ywgGg9OZViwE8KEanLbmP7okgrdcsW4by377oj3VhOC268lRg1Tn/te0vnYKCYUBXt/DC/GrmTk1cHibLysDZgAACAZB1gMwDVBACAIbk7JlDkHxvGtg/55ybObM6dwGpNGWzC4phTSUoY3R9lCmBYFWp34gaTr+unPIvJelf9U/JzoPJIg6/bduIuzGZwvBJMuRpLoM2UzJQHQu/540ICAsYrd8j93IOPTUV28/cTXr3yt/CRtZCxz9FeocWtpEjrMdkzQFephn2yP7LmxfcF/TWIyXTiMM9rLOlKIJZLaBCIPtNRE4/Zo+02/8LDuhwox5hmMp5b26nXLJlQORFUrdjNOz050WcPx6na/YoRj0ypTLw/t2eqiRefn4aMCyWuA6qJB9WL+0AVkH/5nVOF8tsaQhPXObUt0BM3uHUHIt8ZluAEdcWvcL496GQmfhxxClkTR55cMmRUmSi82TXhesW8PD5KAA/OnPPqdpgqyu/fDuCGOX2VeCXuJg0wvA+aUpvQaCiZfdQ2tBX43U3gSHadXiGLl5fqwYxvovrHwGhVLvm4xlTMRO5CSlldS26uLlLhK1VA1qFbkCW0HPCFLe+Gzo8kkpcZ3f8/DHxQd+0b6KJeG5pltAsNEJbsw4Pqe3CqjMSOgyJUajcMFtKKhsf6YTF3H5AS0lR0I7wdPRGbmkX4fTwggsPUJENHxRQpBkRZd6QVRFLV/WE4grk1shuIRtJ2jujOaQ6NEynq7heufeOaa4XGNBWVAM6ajZ0zIG5Zs9SJh6QZqmNb4Lg5btcpazOAI=
Content-Length: 4194304
Content-Range: bytes 0-4194303/4755367
Content-Type: application/x-www-form-urlencoded
Expect: 100-continue
```

**Comment by daryltt** [comment]
I would say this is a separate issue.  This issue is regarding Microsoft Graph API not the OneDrive API.

**Comment by ificator** [comment]
@sameernyaupane If you got the api.onedrive.com URL from graph, then you shouldn't provide the authorization header (the token you have is most likely for graph and not api.onedrive.com). Do things work if you don't provide it?

**Comment by sameernyaupane** [comment]
thanks @ificator! Finally the upload process worked perfectly. It was indeed due to the Authorization header. As soon as I removed it, it worked.

**Comment by Lauragra** [comment]
Looks like this issue is resolved so closing. Thanks.
