### ISSUE TITLE
Getting 401 unauthorized error  with https://graph.microsoft.com/beta/invitations

### ISSUE THREAD

**Issue by rakheejain** [microsoftgraph/microsoft-graph-docs#716]
Hi
I'm getting 401 unauthorized error with https://graph.microsoft.com/beta/invitations graph api using my console application in c#. I've provided below permissions to application registered on Azure AD:

Permission given to Graph API attached in the file:
[permission to GraphAPI.docx](https://github.com/microsoftgraph/microsoft-graph-docs/files/654217/permission.to.GraphAPI.docx)

I'm able to call the API with v1.0 version such as:

- https://graph.microsoft.com/v1.0/users/test@testdomain.com/sendMail
- https://graph.microsoft.com/v1.0/groups/0154403c-e0f6-4045-bc06-5943ab4aa06f/members

Code snippet to call the API:
public static async Task SendInvitation(string accessToken)
        {
            try
            {
                var restURL = "https://graph.microsoft.com/beta/invitations/";
                 using (HttpClient client = new HttpClient())
                 {
                     client.DefaultRequestHeaders.Add("Accept", "application/json");
                     client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);

                     Invite invitation = new Invite();
                     invitation.invitedUserDwrerwerisplayName = "Rakhi Jain";
                     invitation.invitedUserEmailAddress = "test@gmail.com";
                     invitation.inviteRedirectUrl = "https://steria.sharepoint.com";
                     invitation.sendInvitationMessage = true;

                     string postBody = JsonConvert.SerializeObject(invitation);
                    using (var response = await client.PostAsync(restURL, new StringContent(postBody, Encoding.UTF8, "application/json")))
                     {
                         if (response.IsSuccessStatusCode)
                             return;
                     }
                 }

              
            }
            catch (Exception ex)
            {
            }
        }

**Comment by thivy** [comment]
I am also getting 401 when using the beta OneNote Graph API. 

I'm using the Active Directory Authentication Library for .Net to retrieve a Token. 
https://docs.microsoft.com/en-gb/azure/active-directory/active-directory-authentication-libraries

Should i be using any other libraries to get a token?

**Comment by gshreenivasan** [comment]
beta/invitations throws 401-Unauthorized from graph explorer. beta/me works ok. Where exactly do we need to grant this permission to POST using beta/invitations? I am a global administrator in my AD. Thanks

**Comment by rakheejain** [comment]
Hi

I'm now able to run  https://graph.microsoft.com/beta/invitations API.
The issue was with the permission given to the app on azure AD.
Azure application registered on Azure AD needs to provide the below permissions under Microsoft Graph API:
**Read and Write all users' full profile**
![attachfilehandler](https://cloud.githubusercontent.com/assets/20062769/21926224/d5843c6a-d9a6-11e6-9e2e-18d0873b313c.png)

**Comment by gshreenivasan** [comment]
If I am trying from Graph Explorer, can anyone tell me what permissions I have to grant, I used to get 401, now I get "405 MethodNotAllowed" exception. I assigned all the above permissions for Graph API.

**Comment by gshreenivasan** [comment]
I figured out from documentation that a) it will not work from Graph Explorer yet - only GET requests are supported b) Granting permissions as described by Rakhee works - just remember you cannot impersonate as logged in user, you have to use client secret. Thanks everyone!

**Comment by Lauragra** [comment]
It sounds like this issue is resolved so closing for now. Feel free to reopen if you have further questions. Thanks.

**Comment by jrsession** [comment]
I am still getting 401 with azure   var restURL = "https://graph.microsoft.com/beta/invitations/";
is it confirmed this is working ?

**Comment by rakheejain** [comment]
Yes, I'm currently using Graph B2B invitation API and it working perfectly fine at my end. The error 401 is related to permissions and access token. Would suggest you to check the permissions given on AAD application. you can also try running the API using Graph Explorer [https://developer.microsoft.com/en-us/graph/graph-explorer]

**Comment by numino-deepika** [comment]
Still it gives the same error

**Comment by andreyblackberry** [comment]
Hi,

I am trying to list my contacts with  'me/contacts' and still having 401.

My application on apps.dev.microsoft.com has permissions:
  - Contacts.ReadWrite (both delegated and application permissions)

My client application has authentication scope: https://graph.microsoft.com/Contacts.ReadWrite

Other API, like 'me' works fine.

**Comment by JyotiBSingh** [comment]
I am getting 401 while calling https://graph.microsoft.com/v1.0/me or https://graph.microsoft.com/v1.0/me/photo/$value

Code snippet:

 HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, " https://graph.microsoft.com/v1.0/me");
                request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", Session["token"].ToString());
             
                http.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
              
                HttpResponseMessage response = await http.SendAsync(request);
                if (response.IsSuccessStatusCode)
                {
}

I have added all permission in portal . Still unable to resolve.
