### ISSUE TITLE
Assign Claims Mapping Policy

### ISSUE THREAD

**Issue by chrisappianti** [microsoftgraph/microsoft-graph-docs#7936]
Cannot use the method "await graphClient.ServicePrincipals["{id}"].ClaimsMappingPolicies.Request().AddAsync(claimsMappingPolicy);". Is this method missing or is there another way to assign a claims mapping policy to a service principal?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30af93d9-4720-8376-d24e-6e8d33fe69ed
* Version Independent ID: de36d578-1a56-eb3f-a417-4c71ce17c31d
* Content: [Assign claimsMappingPolicy - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-post-claimsmappingpolicies?view=graph-rest-beta&tabs=csharp#feedback)
* Content Source: [api-reference/beta/api/serviceprincipal-post-claimsmappingpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/serviceprincipal-post-claimsmappingpolicies.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by darrelmiller** [comment]
@chrisappianti The example is wrong in beta.  It has been corrected in the V1.0 docs https://docs.microsoft.com/en-us/graph/api/serviceprincipal-post-claimsmappingpolicies?view=graph-rest-1.0&tabs=csharp  

It should get fixed in the beta too /cc @sureshja

**Comment by luleonpla** [comment]
@darrelmiller I still get the same error using the syntax in the v1.0 docs and using the v1.0 MS Graph client.

![MicrosoftTeams-image (14)](https://user-images.githubusercontent.com/22843225/89445112-91dacd00-d707-11ea-8f1b-587a112afdf0.png)

**Comment by davidmu1** [comment]
Revised the beta article.
