### ISSUE TITLE
Not receiving any webhook notifications /communications/callRecords

### ISSUE THREAD

**Issue by Bjoern01** [microsoftgraph/microsoft-graph-docs#9502]
Today at 03:00am we received the last request of the callRecords webhook.
Subscribing to the webhook still works, but it is never called.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6133a73b-23a9-7fa2-78c8-680204490ac0
* Version Independent ID: 413b2545-44cc-1f43-3feb-2c4deab9472e
* Content: [Working with the call records API in Microsoft Graph - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/callrecords-api-overview.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @stephenjust
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by julienFlexsoft** [comment]
Same thing here, subscriptions were made through the Graph API. We made multiple calls in the last six hours and our webhook endpoint didn't even fire once. Is there an issue on Microsoft's side?

**Comment by stephenjust** [comment]
There is currently an ongoing issue.

The related post is TM220340 in the M365 Admin Center.

(I'm aware that currently that post doesn't really make sense, I'll work with our comms team to try to fix it.)

**Comment by stephenjust** [comment]
Comms post should be fixed. You can follow that for updates.

**Comment by apitts** [comment]
TM220340 has been marked as closed in M365 Admin Center. However, I'm still not seeing call records posted to a subscription after more than 60 minutes.

**Comment by GageAmes** [comment]
@apitts I would first check whether your subscription has expired (see [Maximum length of subscription per resource type](https://docs.microsoft.com/graph/api/resources/subscription#maximum-length-of-subscription-per-resource-type)) and try creating a new subscription.

If you still have service issues and want to raise a support request, and if one of the following applies:
- You are an administrator of an active Azure subscription - raise a new technical support ticket at the **[Azure Admin Center](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/newsupportreq)**.
- You are an administrator of an Office 365 or Microsoft 365 tenant - raise a new service request using the **Support** menu in the **[Microsoft 365 Admin Center](https://admin.microsoft.com)**.

**Comment by apitts** [comment]
Thanks @GageAmes! We have already lodged a support ticket. I'm going to try again soon.
